services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
          UID: "${UID}"
          GID: "${GID}"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    environment:
        - PHP_IDE_CONFIG=serverName=docker
#        - XDEBUG_CONFIG="idekey=PHPSTORM"
        - UID=1000
        - GID=1000
  nginx:
    build:
        context: ./docker/nginx
        dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
#      - ./docker/nginx/php-fpm.conf:/etc/nginx/conf.d/php-fpm.conf
#      - ./docker/nginx/octane.conf:/etc/nginx/conf.d/octane.conf
    networks:
      - laravel

  postgres:
      image: postgres:latest
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: rootpass
      volumes:
          - pgdata:/var/lib/postgresql/data
          - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      networks:
          - laravel
networks:
  laravel:

volumes:
  pgdata:
